spring.application.name=userService
spring.datasource.username=postgres
spring.datasource.password=1234

server.servlet.context-path=/api/v1/users
server.port=9020

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userDb

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
spring.jwt.secret-key=U8fDs93nd9s7F3kzLpWmVcYt7xAzGq1M

